#! /usr/bin/env python
import numpy as np
import sys
import libCheckIndex
import matplotlib.pyplot as plt

import readline, glob
def complete(text, state):
    return (glob.glob(text+'*')+[None])[state]

readline.set_completer_delims(' \t\n;')
readline.parse_and_bind("tab: complete")
readline.set_completer(complete)

print "--- Blazar++ check index ---"

FILES = []
TYPE = []
INDEX = []
INDEXTYPE = []

def interactiveRun( ):
    doFlag = True
    while doFlag:
        filename = raw_input('Filename: ')
        FILES.append(filename)
        while True:
            type = raw_input('Type [ele/lum]: ')
            if type == 'ele' or type == 'lum':
                TYPE.append(type)
                break;
            else:
                print 'Please use type \'ele\' or \'lum\'.'
        index = np.array( raw_input('Index to check: ').split(' ') )
        INDEX.append( index )
        while True:
            type = raw_input('Index type [ele/lum]: ')
            if type == 'ele' or type == 'lum':
                INDEXTYPE.append(type)
                break;
            else:
                print 'Please use type \'ele\' or \'lum\'.'
	
        choice = raw_input('Any other file? [y/n] ')
        if choice == 'y' or choice == 'Y':
            doFlag = True
        if choice == 'n' or choice == 'N':
            doFlag = False

def commandlineRun():
    FILES.append( sys.argv[1] )
    if sys.argv[2] == 'ele' or sys.argv[2] == 'lum':
        TYPE.append( sys.argv[2] )
    else:
        print 'Please use type \'ele\' or \'lum\'. Quit.'
        sys.exit()
    INDEX.append( [float(sys.argv[3])] )       
    if sys.argv[2] == 'ele' or sys.argv[2] == 'lum':
        INDEXTYPE.append( sys.argv[4] )
    else:
        print 'Please use type \'ele\' or \'lum\'. Quit.'
        sys.exit()

if len(sys.argv) == 5:
    commandlineRun()
else:
    interactiveRun()


print FILES
FIGURE_LIST = []
OBJECT_LIST = []
print "Check:"
for i in range(len(FILES)):
    print '->', TYPE[i], FILES[i], 'with', INDEXTYPE[i], 'index: ', INDEX[i] 
    FIGURE_LIST.append( plt.figure(i) )
    OBJECT_LIST.append( libCheckIndex.checkIndex(TYPE[i],FILES[i],FIGURE_LIST[i]) )
    OBJECT_LIST[i].addIndex(INDEX[i],INDEXTYPE[i])
    OBJECT_LIST[i].findIndex()
    OBJECT_LIST[i].plot()
#    choice = raw_input('Change index? [y/n] ')
#    if choice == 'n' or choice == 'N':
#            break;

plt.show()
